// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenS4L.Database;

#nullable disable

namespace OpenS4L.Database.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    [Migration("20260819165627_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenS4L.Database.Game.ChannelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MaxLevel")
                        .HasColumnType("integer");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("PlayerLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("channels");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanBanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("integer");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerId");

                    b.ToTable("clan_bans");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Activity")
                        .HasColumnType("smallint");

                    b.Property<string>("Announcement")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<byte>("Area")
                        .HasColumnType("smallint");

                    b.Property<byte>("Class")
                        .HasColumnType("smallint");

                    b.Property<long>("CreationDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Question1")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Question2")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Question3")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Question4")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Question5")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<byte>("RequiredLevel")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("clans");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClanId")
                        .HasColumnType("integer");

                    b.Property<long>("Date")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Type")
                        .HasColumnType("smallint");

                    b.Property<long>("Value1")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerId");

                    b.ToTable("clan_events");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanMemberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer1")
                        .HasColumnType("text");

                    b.Property<string>("Answer2")
                        .HasColumnType("text");

                    b.Property<string>("Answer3")
                        .HasColumnType("text");

                    b.Property<string>("Answer4")
                        .HasColumnType("text");

                    b.Property<string>("Answer5")
                        .HasColumnType("text");

                    b.Property<int>("ClanId")
                        .HasColumnType("integer");

                    b.Property<long>("JoinDate")
                        .HasColumnType("bigint");

                    b.Property<long>("LastLoginDate")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("Role")
                        .HasColumnType("smallint");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ClanId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("clan_members");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.LevelRewardEntity", b =>
                {
                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("Money")
                        .HasColumnType("integer");

                    b.Property<byte>("MoneyType")
                        .HasColumnType("smallint");

                    b.HasKey("Level");

                    b.ToTable("level_rewards");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerCharacterEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccessoryId")
                        .HasColumnType("bigint");

                    b.Property<byte>("BasicFace")
                        .HasColumnType("smallint");

                    b.Property<byte>("BasicHair")
                        .HasColumnType("smallint");

                    b.Property<byte>("BasicPants")
                        .HasColumnType("smallint");

                    b.Property<byte>("BasicShirt")
                        .HasColumnType("smallint");

                    b.Property<long?>("FaceId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Gender")
                        .HasColumnType("smallint");

                    b.Property<long?>("GlovesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("HairId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PantsId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PetId")
                        .HasColumnType("bigint");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long?>("ShirtId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ShoesId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SkillId")
                        .HasColumnType("bigint");

                    b.Property<byte>("Slot")
                        .HasColumnType("smallint");

                    b.Property<long?>("Weapon1Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Weapon2Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("Weapon3Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryId");

                    b.HasIndex("FaceId");

                    b.HasIndex("GlovesId");

                    b.HasIndex("HairId");

                    b.HasIndex("PantsId");

                    b.HasIndex("PetId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShirtId");

                    b.HasIndex("ShoesId");

                    b.HasIndex("SkillId");

                    b.HasIndex("Weapon1Id");

                    b.HasIndex("Weapon2Id");

                    b.HasIndex("Weapon3Id");

                    b.ToTable("player_characters");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerDenyEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("DenyPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DenyPlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_deny");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AP")
                        .HasColumnType("integer");

                    b.Property<int>("Coins1")
                        .HasColumnType("integer");

                    b.Property<int>("Coins2")
                        .HasColumnType("integer");

                    b.Property<byte>("CurrentCharacterSlot")
                        .HasColumnType("smallint");

                    b.Property<int>("PEN")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExperience")
                        .HasColumnType("integer");

                    b.Property<byte>("TutorialState")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("players");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerFriendEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("FriendPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<byte>("State")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FriendPlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_friends");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Color")
                        .HasColumnType("smallint");

                    b.Property<int>("Durability")
                        .HasColumnType("integer");

                    b.Property<string>("Effects")
                        .HasColumnType("text");

                    b.Property<int>("MP")
                        .HasColumnType("integer");

                    b.Property<int>("MPLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("PurchaseDate")
                        .HasColumnType("bigint");

                    b.Property<int>("ShopItemInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopPriceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ShopItemInfoId");

                    b.HasIndex("ShopPriceId");

                    b.ToTable("player_items");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerMailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsMailDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMailNew")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderPlayerId")
                        .HasColumnType("integer");

                    b.Property<long>("SentDate")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SenderPlayerId");

                    b.ToTable("player_mails");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerSettingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("player_settings");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopEffectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Effect")
                        .HasColumnType("bigint");

                    b.Property<int>("EffectGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EffectGroupId");

                    b.ToTable("shop_effects");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopEffectGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("PreviewEffect")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shop_effect_groups");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Colors")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsDestroyable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOneTimeUse")
                        .HasColumnType("boolean");

                    b.Property<byte>("LevelLimit")
                        .HasColumnType("smallint");

                    b.Property<byte>("MainTab")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequiredGender")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequiredLevel")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequiredLicense")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequiredMasterLevel")
                        .HasColumnType("smallint");

                    b.Property<byte>("SubTab")
                        .HasColumnType("smallint");

                    b.Property<byte>("UniqueColors")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("shop_items");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopItemInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("DiscountPercentage")
                        .HasColumnType("smallint");

                    b.Property<int>("EffectGroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PriceGroupId")
                        .HasColumnType("integer");

                    b.Property<long>("ShopItemId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EffectGroupId");

                    b.HasIndex("PriceGroupId");

                    b.HasIndex("ShopItemId");

                    b.ToTable("shop_iteminfos");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopPriceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Durability")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("boolean");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<byte>("PeriodType")
                        .HasColumnType("smallint");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<int>("PriceGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PriceGroupId");

                    b.ToTable("shop_prices");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopPriceGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<byte>("PriceType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("shop_price_groups");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopVersionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("shop_version");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.StartItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte>("Color")
                        .HasColumnType("smallint");

                    b.Property<byte>("RequiredSecurityLevel")
                        .HasColumnType("smallint");

                    b.Property<int>("ShopItemInfoId")
                        .HasColumnType("integer");

                    b.Property<int>("ShopPriceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemInfoId");

                    b.HasIndex("ShopPriceId");

                    b.ToTable("start_items");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanBanEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ClanEntity", "Clan")
                        .WithMany("Bans")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanEventEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ClanEntity", "Clan")
                        .WithMany("Events")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanMemberEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ClanEntity", "Clan")
                        .WithMany("Members")
                        .HasForeignKey("ClanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithOne("ClanMember")
                        .HasForeignKey("OpenS4L.Database.Game.ClanMemberEntity", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clan");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerCharacterEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Accessory")
                        .WithMany()
                        .HasForeignKey("AccessoryId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Face")
                        .WithMany()
                        .HasForeignKey("FaceId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Gloves")
                        .WithMany()
                        .HasForeignKey("GlovesId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Hair")
                        .WithMany()
                        .HasForeignKey("HairId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Pants")
                        .WithMany()
                        .HasForeignKey("PantsId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId");

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Shirt")
                        .WithMany()
                        .HasForeignKey("ShirtId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Shoes")
                        .WithMany()
                        .HasForeignKey("ShoesId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Weapon1")
                        .WithMany()
                        .HasForeignKey("Weapon1Id");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Weapon2")
                        .WithMany()
                        .HasForeignKey("Weapon2Id");

                    b.HasOne("OpenS4L.Database.Game.PlayerItemEntity", "Weapon3")
                        .WithMany()
                        .HasForeignKey("Weapon3Id");

                    b.Navigation("Accessory");

                    b.Navigation("Face");

                    b.Navigation("Gloves");

                    b.Navigation("Hair");

                    b.Navigation("Pants");

                    b.Navigation("Pet");

                    b.Navigation("Player");

                    b.Navigation("Shirt");

                    b.Navigation("Shoes");

                    b.Navigation("Skill");

                    b.Navigation("Weapon1");

                    b.Navigation("Weapon2");

                    b.Navigation("Weapon3");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerDenyEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "DenyPlayer")
                        .WithMany()
                        .HasForeignKey("DenyPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Ignores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DenyPlayer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerFriendEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "FriendPlayer")
                        .WithMany()
                        .HasForeignKey("FriendPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Friends")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FriendPlayer");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerItemEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Items")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.ShopItemInfoEntity", "ShopItemInfo")
                        .WithMany()
                        .HasForeignKey("ShopItemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.ShopPriceEntity", "ShopPrice")
                        .WithMany()
                        .HasForeignKey("ShopPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("ShopItemInfo");

                    b.Navigation("ShopPrice");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerMailEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Inbox")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "SenderPlayer")
                        .WithMany()
                        .HasForeignKey("SenderPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("SenderPlayer");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerSettingEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.PlayerEntity", "Player")
                        .WithMany("Settings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopEffectEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ShopEffectGroupEntity", "EffectGroup")
                        .WithMany("ShopEffects")
                        .HasForeignKey("EffectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffectGroup");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopItemInfoEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ShopEffectGroupEntity", "EffectGroup")
                        .WithMany()
                        .HasForeignKey("EffectGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.ShopPriceGroupEntity", "PriceGroup")
                        .WithMany()
                        .HasForeignKey("PriceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.ShopItemEntity", "ShopItem")
                        .WithMany("ItemInfos")
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EffectGroup");

                    b.Navigation("PriceGroup");

                    b.Navigation("ShopItem");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopPriceEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ShopPriceGroupEntity", "PriceGroup")
                        .WithMany("ShopPrices")
                        .HasForeignKey("PriceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceGroup");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.StartItemEntity", b =>
                {
                    b.HasOne("OpenS4L.Database.Game.ShopItemInfoEntity", "ShopItemInfo")
                        .WithMany()
                        .HasForeignKey("ShopItemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpenS4L.Database.Game.ShopPriceEntity", "ShopPrice")
                        .WithMany()
                        .HasForeignKey("ShopPriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItemInfo");

                    b.Navigation("ShopPrice");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ClanEntity", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Events");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.PlayerEntity", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ClanMember");

                    b.Navigation("Friends");

                    b.Navigation("Ignores");

                    b.Navigation("Inbox");

                    b.Navigation("Items");

                    b.Navigation("Settings");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopEffectGroupEntity", b =>
                {
                    b.Navigation("ShopEffects");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopItemEntity", b =>
                {
                    b.Navigation("ItemInfos");
                });

            modelBuilder.Entity("OpenS4L.Database.Game.ShopPriceGroupEntity", b =>
                {
                    b.Navigation("ShopPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
