<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>1998</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DotNetty.Handlers" Version="0.7.6" />
    <PackageReference Include="Iconic.Zlib.Netstandard" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.2" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Logging\Logging.csproj" />
    <ProjectReference Include="..\OpenS4L.Blub\OpenS4L.Blub.csproj" />
  </ItemGroup>
</Project>
