<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Portable.BouncyCastle" Version="1.8.1.3" />
    <PackageReference Include="SharpLzo" Version="0.1.2" />
    <PackageReference Include="System.Numerics.Vectors" Version="4.4.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpenS4L.Blub\OpenS4L.Blub.csproj" />
  </ItemGroup>
</Project>
