using System.Text;
using System.Text.RegularExpressions;

namespace S4LLegacyMigration;

/// <summary>
/// Converts a legacy MySQL data dump (INSERT ... VALUES ...) into PostgreSQL-compatible SQL.
/// v1.0: handles standard mysqldump INSERT statements, backtick identifiers, quoted escapes
/// (\' \"), and NULL literals. Returns a re-written script meant to be run with psql after the
/// destination tables already exist.
/// </summary>
public sealed class DumpConverter
{
    public int InsertStatements { get; private set; }
    public int UnhandledLines { get; private set; }

    private static readonly Regex InsertRe = new(
        @"^\s*INSERT\s+INTO\s+`?([A-Za-z0-9_]+)`?\s*\(([^)]*)\)\s*VALUES\s*(.*?);\s*$",
        RegexOptions.IgnoreCase | RegexOptions.Singleline | RegexOptions.Compiled);

    private static readonly Regex SetRe = new(
        @"^\s*SET\s+@?(?:[\w@]+\s*=\s*)?[^;]+;",
        RegexOptions.IgnoreCase | RegexOptions.Compiled);

    public string Convert(string input, string? tableFilter = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("-- Generated by S4LLegacyMigration");
        sb.AppendLine("-- Converted from a legacy NetspherePirates MySQL data dump.");
        sb.AppendLine("-- Requires destination tables to already exist in the OpenS4L PostgreSQL DB.");
        sb.AppendLine("BEGIN;");
        sb.AppendLine();

        var lines = input.Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            var line = lines[i];
            // Fold multi-line INSERT ... VALUES;... statements.
            var statement = line;
            var m = InsertRe.Match(statement);
            if (!m.Success && line.Contains("INSERT", StringComparison.OrdinalIgnoreCase) && !line.TrimEnd().EndsWith(';'))
            {
                // Accumulate until a ';' at the end of a line.
                var sbAcc = new StringBuilder(line);
                int j = i + 1;
                while (j < lines.Length)
                {
                    var l = lines[j];
                    sbAcc.Append('\n').Append(l);
                    if (l.TrimEnd().EndsWith(';')) break;
                    j++;
                }
                i = j;
                statement = sbAcc.ToString();
                m = InsertRe.Match(statement);
            }

            if (m.Success)
            {
                var table = m.Groups[1].Value.ToLowerInvariant();
                if (tableFilter is null || string.Equals(table, tableFilter, StringComparison.OrdinalIgnoreCase))
                {
                    var cols = NormalizeColumns(m.Groups[2].Value);
                    var values = NormalizeValues(m.Groups[3].Value);
                    sb.AppendLine($"INSERT INTO \"{table}\" ({cols}) VALUES {values};");
                    InsertStatements++;
                    continue;
                }
            }

            if (SetRe.IsMatch(line))
            {
                // Skip SET NAMES / SET FOREIGN_KEY_CHECKS / variable assignments.
                continue;
            }

            // Copy through headers, comments, blank lines.
            if (line.TrimStart().StartsWith("--") || string.IsNullOrWhiteSpace(line))
            {
                sb.AppendLine(line);
                continue;
            }

            UnhandledLines++;
        }

        sb.AppendLine();
        sb.AppendLine("COMMIT;");
        return sb.ToString();
    }

    private static string NormalizeColumns(string raw)
    {
        // `col1`,`col2` -> "col1","col2" (lower-cased, unquoted-safe).
        return Regex.Replace(raw, "`?([A-Za-z0-9_]+)`?", m => $"\"{m.Groups[1].Value.ToLowerInvariant()}\"");
    }

    private static string NormalizeValues(string raw)
    {
        var v = raw.Trim();
        // MySQL string escapes: \' -> '', \" -> ", \\ -> \\, \n stays.
        v = v.Replace("\\'", "''").Replace("\\\"", "\"").Replace("\\\\", "\\\\");
        return v;
    }
}
